global:
    namespace: ENC[AES256_GCM,data:9jgqQizI,iv:qTdhGAdd+Fi06QpJpNG2WC+lFJ/DRLNViM0OJYWuZ1s=,tag:Cpf63CRPYwORALOwQ6Tdsg==,type:str]
jupyterhub:
    vlabs:
        openlab:
            image:
                tag: ENC[AES256_GCM,data:Xgt+CHeJug==,iv:HyuciYg2Fmj/sjLMJiX/pdoHjto8fJJGNKa/96RWL6U=,tag:wSHFdfg2l595exNDlwnQFA==,type:str]
            configuration:
                base_image_tags_url: ENC[AES256_GCM,data:JIsAoijUGQnoSfH+S6OwNM1b78XaZTBo1tGhyC3RjK5TxUP9M44LrZNGfvHnxs29Fp50fYh1j5b6FUZntluV2IQR5ZN0E8gSI34VhJrOOOo=,iv:eohDqrBjztZowv8H1/I4Gpq4joh4IiJd8A8THAmXcfM=,tag:9aN+/rmbJu1y58wE0Tdc9Q==,type:str]
                cell_github_url: ENC[AES256_GCM,data:WVTy7iM/MEIy1cXH1XfDyyo/WXs8as5rtRSyWvbSUbi8E0A3QufOUqeS7so=,iv:Wm0ggUvH7f3sz7vCDP4ZBC3ETIbph8Fts7eYPNcR2pw=,tag:PXv104Kp2Za1vHXgNS4JlQ==,type:str]
                cell_github_token: ENC[AES256_GCM,data:VaOMkhme63W6PE3P1VA0y6/C9nurXxwENSPJTVNEBEjSNbJkaMpmsw==,iv:U2k+v+lhyAyzJTI4I5+8kznmIwvYdURwv2k62/UK3EE=,tag:fyLA8nKfWp5pTXG5sKqoKg==,type:str]
                registry_url: ENC[AES256_GCM,data:iQr+JYcDwSJ8biy5AM5AJv1Rs+OeO9NZsfiR7LAjgp3/,iv:JN4rvbb17Z/TxWkZb+LRSuCzkEcYDLvODubLvQr+sUU=,tag:p67aGAQ3wimhKXMYL5+rVQ==,type:str]
naavreContainerizerService:
    enabled: ENC[AES256_GCM,data:FsSaww==,iv:/M76EcchrSLkhsIvJ9EcwSpHFENAs9kBNilZLTHIHmE=,tag:4IN7O/r1j5CX0dHjIK8JUg==,type:bool]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:050752621342:key/4680e482-89c6-4210-b541-0453aa4a41ef
          created_at: "2025-11-13T12:00:46Z"
          enc: AQICAHhTmJtY4jHaV3j5UYiXyuOv54scxHoIVc/S99cT0IZ1IwF1mrxyuCEuzbUjXxcJ5nyhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1CmWUf45pcbnsGysAgEQgDtp85N+Zr2k2GOz5MfTVcylknAWRlgkpiqw6BikVPj6pdlsOcC4rd2z9mv3tDfqC59Xjtp40dwnTDIQrg==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:050752621342:key/6a9ef814-a13a-4299-b406-2e75b3ef1554
          created_at: "2025-11-13T12:00:46Z"
          enc: AQICAHi22G6tOL2LsvF6wpMHn/yuAwEASofH+f0dK2WYCvRIlQFKy+KsGup2RwsHUItLLd09AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDbc8JCZEDF8NcEUUAgEQgDvE+9877y6NsCfKDbCAdzRY7RpLV2e7V+rW7JKGqr0ELrx9L0IOpJ7vc7xbrrib+5jcPE6089yi+I3Quw==
          aws_profile: ""
    lastmodified: "2025-11-13T15:56:13Z"
    mac: ENC[AES256_GCM,data:xCPOvbu1b2JvdqmPzYIYrY5YwqCm3DP96HsMg1xj6N3HVDJqk1K8lRmM9W5RNlkXnsgGLgjxO94zMjJog3oasKbgrWSMYYNGV95+Q3GBVVxJqh7r9aEySuSuu7m07LyT6xVv/QxM3tIYNhszLhVwVZi0NSWiUW7OnJT3WPMq53E=,iv:s0eFnvRNNZdtmAq5Wt0832kZjhyMcpm++k7CEaqK6RI=,tag:owLSqXE0L6buHZclxvEeVA==,type:str]
    pgp:
        - created_at: "2025-11-13T12:00:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdjO6979FjmkSAQdAkrVG9SQviBtcpbSxn0ycGFWytf8EfjfqmrkRKDLRBWcw
            SmfiOK94Lo2exEoYWPNnBAuBcfAUBTRqov7ZKqPktoQYze3WRQzdeZErWNYn85/8
            1GYBCQIQjlWu3fhttHuG6DEHnurXVEqBid21MwiIkA5HIAMEh6HJ7OOsjD3D2/Jv
            XjaTtqL2JJ0rjX5GoRV2J48XpKTPMHQGe171oQSkNtsQoPYvCBoTMY7CZISJ4Poq
            E/MhjFz9scM=
            =bRH7
            -----END PGP MESSAGE-----
          fp: E90351D346AFCF25477190F1434316312E1CF3B1
    unencrypted_suffix: _unencrypted
    version: 3.10.2
