global:
    namespace: ENC[AES256_GCM,data:28ZqCaL7,iv:RzkeBLcKUFZnK1j5Q92ExFdmZQeR2ZZd9deNNKJtwS4=,tag:fJKJ7/7QekDesZLYtXxGHg==,type:str]
    #ENC[AES256_GCM,data:mOaimR1mjFweclRW3RL9MrfAIhRQZ8FdIcBhvz0SycCrWIMw9Pv7/9eqBOP9v4/LtlVlT43FYe9Z3KWjJRNR7V4F,iv:uzPdqlGvrDUmKVXuAKFMCXguogwBTKpdlyPIPExTizA=,tag:/yfuxVWvg/pcErBk5yEcMA==,type:comment]
    insecureSkipVerifySSL: ENC[AES256_GCM,data:hsfU6A==,iv:qPTkbHnXu2Lf/cTKdzlveoOhT4IuM7Hr+MhRv3930c0=,tag:bc1P8wX/uiwq2B3dghf9Nw==,type:bool]
    ingress:
        domain: ENC[AES256_GCM,data:4IaW8sxnxMjtUHgCHbqzC5PEOqtJOUS0,iv:NIanHgmmpy8OwgJdE0lBKX0eGo6jbbOt/kX+/71MIn4=,tag:C57oDvGmbmi9H/+Iq4equQ==,type:str]
        commonAnnotations: {}
        tls:
            enabled: ENC[AES256_GCM,data:9NfR/oM=,iv:Wx0YwdIPsGBdOBh8jQ5bZZgnRv6jQCrEVBwR5G9kLQw=,tag:3XnrC5h8Z0zCXSq8NU/06Q==,type:bool]
    secrets:
        k8sSecretCreator:
            apiToken: ENC[AES256_GCM,data:yTSl3d+tLTOsgsQG3RJmPyt+PtFJtcISAiCzgB86Sv7AjGw=,iv:MpXQgJJSDkxlSbN8qMOk6fyOvaZLJWCvx/UKd6gRPbw=,tag:74qRKV1eu/lxAtmNvFJmqQ==,type:str]
        naavreCatalogueService:
            secretKey: ENC[AES256_GCM,data:EZLdYPAW9lLLJ8OkMZbX+PskP7HOUklVq34DwI5bXk+zGZV1unYiSl8c,iv:08QhRaNCyImjheW3m6Fl3ucHPuOnKRQscCxv5mN1KtY=,tag:zvQmVSWSQaION70G+2xFcA==,type:str]
            auth:
                superuser:
                    email: ENC[AES256_GCM,data:abT85+gqj/pfSUth1EGC/MY=,iv:n24syGJSVW5rR18rQYDpcAMzw9iPcRYqSrrCQRIRfME=,tag:g19t3VzoMpJPQ0lRlXolQQ==,type:str]
                    username: ENC[AES256_GCM,data:UQ2S9Jo=,iv:bpaFVHwq3E11w/lC3/skFwGxrRdQ37cl7FYJ95TpWwM=,tag:K/lL0EM2F+DWYQUIblZYzQ==,type:str]
                    password: ENC[AES256_GCM,data:KWZ0eN6BNuoRCfY2S1paX4KRT4xUisvr1Db/1/LIRuIdSgUDC+pM+kYnjlJOTQ==,iv:y+aqeQWWFN8UxWlufHqk6g8GI46IMEMmPWkmgaauaQE=,tag:HuqjbcrwfpTHBDmcOoCxJQ==,type:str]
            postgresql:
                password: ENC[AES256_GCM,data:v++r6G3yKeMoxU1WrdzPVEQh/PA9WBMi4RcmotyDvIfSJiIEq6AKODrogTVt75LEkjxT,iv:lon6fnVrb87Ct2KG/BCBDHABHHQSSARlRMgKlKtYuIo=,tag:fOMa87ZMqOc8cTMvbvgAkw==,type:str]
        naavrePaasFrontend:
            secretKey: ENC[AES256_GCM,data:+U1Was4FyZgTvDnzObLgf3aLMNfqrmlrz29CBbGg01ptmBgQj6Y=,iv:7qWAzn+Hf2xD7vMz/NsW5TyFtC9utmRYO/U9OGwRfa0=,tag:/zq9bSU1HH0vLbDNWE88qw==,type:str]
        keycloak:
            adminPassword: ENC[AES256_GCM,data:3xTyvsNLl6xPJ/aZ2ClvJAFSSWp3JjcqNk2LQyfs,iv:F/rlqA3lZSJsO/BMmohcVFrC6C0oqd9SQxGRF3iFark=,tag:qe2Cx1C3j7l6jlWdV5d5jg==,type:str]
            naavreClientSecret: ENC[AES256_GCM,data:3Sr/DNnLJm+teZ/Ud5QoW0+vjBa/SyNwvRz15YvZko5qsT+W,iv:0x0/vt9N7u8jLksNTlx3+hQK/po+kCiyrpeODEE7K4E=,tag:zIZICqoGvgXJgsH7021mRw==,type:str]
            users:
                - username: ENC[AES256_GCM,data:0QoVCwPtdQ==,iv:jDQxxFy/fgIf4wUncH4XT/ezZf2mSIBYokhLzsAueEM=,tag:mcv4MmzAnSg/sEF6EFI30Q==,type:str]
                  password: ENC[AES256_GCM,data:rW1Ur1Np7hB/f/o=,iv:MRhCUJayLKAABlhq1tu0Q6f+HOB2W2M1pLUPO62PLdk=,tag:vFmd9sQK85n82de/pzQGaw==,type:str]
            postgresql:
                password: ENC[AES256_GCM,data:rY+lvZOu78yfP7mMfUm3EV3GMiLjmV9t6TM9VzVa71BXvQc=,iv:drjLbVx0+CkoH55OSrqOYfCm5tXD6Qyo38314JOTIb4=,tag:KRar12olGhkyfA5yjv1qUA==,type:str]
jupyterhub:
    enabled: ENC[AES256_GCM,data:IgvLhA==,iv:5s+TdGhOBVf9i0jQC1gwB5jOneKOGG38HCJa1pzVgrY=,tag:Fb92z7lNz+VaQQDV2znu5Q==,type:bool]
    vlabs:
        openlab:
            slug: ENC[AES256_GCM,data:dRLipBtmlA==,iv:DXarERokHJMdWoeYIY2s3wnEmOzPFukY5/o1iH/Yxbs=,tag:MOJuHq4TFjKs6I62gK2u0g==,type:str]
            title: ENC[AES256_GCM,data:RqyKimPhkqkp+FLWXWdr,iv:HiI/89QnYEyd0LqV5od8ydGRf+cXYxlA1GmYHRqy6h0=,tag:ruTj1l72IdsHZB7j+0bXKA==,type:str]
            description: ENC[AES256_GCM,data:tGCFVE5yFNz6xspsidztyUhSVmdSaiPYSFvVXF6zRqnUa4WcThg=,iv:9/E04UheXfzsgxGSo1u7qrtbmcUbC74899ftFuAPhms=,tag:7rTuPMF56Q9bvSIWZQeqZw==,type:str]
            image:
                name: ENC[AES256_GCM,data:8LpFfvgjuh+Cmpi9tDFrPRGvcyXyQLamWWxO5PYe7nIx3qL4nXlsWbLXfnluvzAX,iv:3ILn/AhF6kCakeRs4JFj+MVTFLKqnzTxwuR+ci5cC4w=,tag:x5am/Fs/mXK+OOfEbTtIUQ==,type:str]
                tag: ENC[AES256_GCM,data:w/PR25dxMA==,iv:G8mt/6ey0wtu/1IovX2m4ZzaNWhdbMt6ftb+pUUbybk=,tag:MT55Kryr+0vN/4iJeF55dA==,type:str]
            configuration:
                base_image_tags_url: ENC[AES256_GCM,data:QkCPicnJiS8CL79kW2meDO6UgSxB8KGpUwrFWx+CJsLZu+ctBwavzWhatcGOuSANbwreCM4v3JguaWT79aXSPANTxCU5p/DCzfbZQMud5A==,iv:nogXiIJ7ruGCD8f+vMZnqQICyutsPtFrPPwvquq5z1w=,tag:JGskRJ8zpnrNCL7fvfwzig==,type:str]
                module_mapping_url: ENC[AES256_GCM,data:8OLRjhyx/ZVRtW1c5k9vyWH/TIuJSRWbY/QsVIB4rUOAngsNHzMTp5YsPBwXUv5xyFmAbqkWlRtdC3IEW1YWmkHAw1q9O3mZg8xfKQ==,iv:lIMXZ98jk+TbdCOQdmiX5Qj8BzfVgYNLa5Y4tWU8hQU=,tag:8Yb90w6Z4CDcbDcHyRIjUw==,type:str]
                cell_github_url: ENC[AES256_GCM,data:nd/i2z6UCyhNDoVoVQ1a+tugocg4QmvxdRe4adZJCShL4W82DiPA3OshbmM=,iv:RsGzJv6s8gIaHm7F56sMT3KSQZqDx1S+kkHdNNWj3b8=,tag:V15MjOnmhe9j9uIF512U0A==,type:str]
                cell_github_token: ENC[AES256_GCM,data:MoImpEQ1tcON9gUcjDGnerLX+0xsw9F/RBlA5S6ZBbb7T3gNNojihg==,iv:8gw/MWNIMso05fxZ9BqmR6DqkEPq2URHYYea58pwaR4=,tag:tW5bZXiEsq8X6N/3DER3bg==,type:str]
                registry_url: ENC[AES256_GCM,data:ILafN1cf3jcN47QEjsQNPYkM0NtYHniPAoqOBCNJWYeh,iv:Z8vIsH6GRaBWgfn2eYUaBYykIXNpg3h2ZebMZF77JKc=,tag:FdZN3D5YI1pb9MSGj6AQEw==,type:str]
k8sSecretCreator:
    enabled: ENC[AES256_GCM,data:qnh3nw==,iv:KdkZ6u3G8tmEYU6RCnrPW5zZdmKWELcRh2HcnS8h/gE=,tag:HW+8qpz3amlyYJZRB4vh4g==,type:bool]
naavreCatalogueService:
    enabled: ENC[AES256_GCM,data:l0UO1Q==,iv:sqHvkD7Ng6+mj0i2cigCkWqy12wSVR6abgtNoKYYVlM=,tag:bHsq72gwmQTz2aUaVFRLEw==,type:bool]
naavreContainerizerService:
    enabled: ENC[AES256_GCM,data:amC7bzc=,iv:LCsnKbqy1inaOXbdYfD4zKzpsFyn47+hIwHNy0081ZQ=,tag:czEOfUpVKwOo/7LcTI/s1Q==,type:bool]
    debug: ENC[AES256_GCM,data:FTdPNMw=,iv:kTvrdpktUXNprINuJx4wm5l3owe6tG2obR5EfI+MfKg=,tag:yuomr+TUsO8jQ2fzDDnTrg==,type:bool]
naavreWorkflowService:
    enabled: ENC[AES256_GCM,data:W5rVXA==,iv:IsBQ7b8YZWwPl4yiaKzvF4AMbBeURPsnoz5F5F1YVnE=,tag:2UzfRHO8qLqibajLOlpzvA==,type:bool]
naavrePaasFrontend:
    enabled: ENC[AES256_GCM,data:JgfRIg==,iv:9e/+ctgqCRFNGJUO/07kowHp5N/UqDW1hDFR9Q2XndA=,tag:ZGuxks66hwN6hW8Vic5Dgg==,type:bool]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:050752621342:key/4680e482-89c6-4210-b541-0453aa4a41ef
          created_at: "2025-11-12T14:19:07Z"
          enc: AQICAHhTmJtY4jHaV3j5UYiXyuOv54scxHoIVc/S99cT0IZ1IwH1QpqF0xA1RL7SQUdLzUt2AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFUGOunKvngWMh6jWAgEQgDvm6ma0RONS3pW5oXHq+Tv8C7Hxp3NWh3mpqcRuaCxL08+XkDf2iAif4JOKxFEtss78ewqmytjsIHD9kw==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:050752621342:key/6a9ef814-a13a-4299-b406-2e75b3ef1554
          created_at: "2025-11-12T14:19:07Z"
          enc: AQICAHi22G6tOL2LsvF6wpMHn/yuAwEASofH+f0dK2WYCvRIlQHnJEIwgc6Yqi4gmQrY3KtSAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzNNRJ6T0rHI1y9KqAgEQgDtwgnctBIznSu3/je53iL2yAVCuEdy9tO+bUdyogba6193XgpPYf5VtpVfHmgRmJvvOZM155jqk/3YsmA==
          aws_profile: ""
    lastmodified: "2025-11-12T14:19:17Z"
    mac: ENC[AES256_GCM,data:M72R08PyuXm01WBC5exZi9wRYdBgoP1H3dQUa4dF3oUqpFBlcrviisp4g0XpuHHI92CIfyQcwXzYwgbPjhzcDOjV+Dal4ZOm4gYONvCPLqBYh16iA5+mGxBQpBiyfOV2GjTftguevs5NBdWng6JLiigERLNiZgqYzL07kGcxE4o=,iv:HKrt5yvokz0E152dhvO+ysYgR35Izo1B49/+JR/jPzs=,tag:AQWg83a/gfBiQ7dXqB6Z2w==,type:str]
    pgp:
        - created_at: "2025-11-12T14:19:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdjO6979FjmkSAQdAN0h2JIRWrMWhYhnOp6yjscM51UOUX6iL+6GqxGtaXnAw
            J7rmDhkoWl5r5BT5FNIbxFBSQa/VtR3LFh01Du0oZkXYXBqNz4Esbhg6RH9KL5h8
            1GgBCQIQT/UFAjbmNCoDdIW3F77RUTgr0cMQvMrZDa9xg6NYD2U3ciVlkDfA42ez
            +CItjRn9xLe09nJw0gN1XRtIINjz23ROMOgo/Npcq3icDIFHUkT0GT8sIPZvg1/J
            cUkAmc0AePIX0g==
            =4blq
            -----END PGP MESSAGE-----
          fp: E90351D346AFCF25477190F1434316312E1CF3B1
    unencrypted_suffix: _unencrypted
    version: 3.10.2
