global:
    namespace: ENC[AES256_GCM,data:9jgqQizI,iv:qTdhGAdd+Fi06QpJpNG2WC+lFJ/DRLNViM0OJYWuZ1s=,tag:Cpf63CRPYwORALOwQ6Tdsg==,type:str]
jupyterhub:
    vlabs:
        openlab:
            image:
                tag: ENC[AES256_GCM,data:rnPfX8zP,iv:uD785BnxrQjUAMsTP0RhL0AglLufpcVDwAEH+5OW4hQ=,tag:Tbwx1+ezcU2/5gs0kPcJNA==,type:str]
            configuration:
                base_image_tags_url: ENC[AES256_GCM,data:sYF4QaLyu0gHzfZwXoIQDTW/AQexpUJU30AU0k49CjxXeU1G4Ddw4w/gjizAlQwGJ/wC5WmlzqJqHWAFNzl3hG6rNeSCB0XeE9L3NvSOrg==,iv:CB8z+JWJTdzUW0Uj5uz4oEj0G0TMafLNHm0NfvD/3lw=,tag:w+dCRo7qBhyJY8qKEqMkXg==,type:str]
                cell_github_url: ENC[AES256_GCM,data:gpmWrqhx4CEkt0GhfSuDyLH37XxZZ++m0WdyEyXQmzz3rcpb0BphPg==,iv:ZQzsaO2idl0FcVatWKNq4c5hnxVx+ARIiGMB9el/4v0=,tag:Nn+gYmL85pq/w6TmbQX9Tg==,type:str]
                cell_github_token: ENC[AES256_GCM,data:VaOMkhme63W6PE3P1VA0y6/C9nurXxwENSPJTVNEBEjSNbJkaMpmsw==,iv:U2k+v+lhyAyzJTI4I5+8kznmIwvYdURwv2k62/UK3EE=,tag:fyLA8nKfWp5pTXG5sKqoKg==,type:str]
                registry_url: ENC[AES256_GCM,data:jgduUriZKAXBBxnb+7nslAB1qK+0zbUG5h7jIps=,iv:E6YS3j7CypuRMziykoMgMUSKt05L9BxKjbuIgK2ag/I=,tag:fQU0XewE1/+qME7t7b63Mw==,type:str]
naavreContainerizerService:
    enabled: ENC[AES256_GCM,data:diXBaA==,iv:FzTw6ZB1LCKnLHtr6cf5Rd10kcb2+5D+ibYwToM4o+0=,tag:cgC/ULuzfPsCdFKuLEvHDA==,type:bool]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:050752621342:key/4680e482-89c6-4210-b541-0453aa4a41ef
          created_at: "2025-11-13T12:00:46Z"
          enc: AQICAHhTmJtY4jHaV3j5UYiXyuOv54scxHoIVc/S99cT0IZ1IwF1mrxyuCEuzbUjXxcJ5nyhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1CmWUf45pcbnsGysAgEQgDtp85N+Zr2k2GOz5MfTVcylknAWRlgkpiqw6BikVPj6pdlsOcC4rd2z9mv3tDfqC59Xjtp40dwnTDIQrg==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:050752621342:key/6a9ef814-a13a-4299-b406-2e75b3ef1554
          created_at: "2025-11-13T12:00:46Z"
          enc: AQICAHi22G6tOL2LsvF6wpMHn/yuAwEASofH+f0dK2WYCvRIlQFKy+KsGup2RwsHUItLLd09AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDbc8JCZEDF8NcEUUAgEQgDvE+9877y6NsCfKDbCAdzRY7RpLV2e7V+rW7JKGqr0ELrx9L0IOpJ7vc7xbrrib+5jcPE6089yi+I3Quw==
          aws_profile: ""
    lastmodified: "2025-11-21T19:43:23Z"
    mac: ENC[AES256_GCM,data:VN9x5yGiVwwq8LOUSbry5OGg2M9kDeHggXdQjEvI4yNDHteembUqLMF736tJwHSoDyq96VoU5BsGCHV8YTWp9huCEgq4MV5ZpFxiX7Y0j1d/w9bS5zlm39JOEb7/S8AqCYzKbbQSIJIN0kmz56LASZPlPr1/lAgc/+gS7s3zahw=,iv:Nf29vjH6tEq0AiikNUTKk3vM6BKD2v46sQk96LXlR4U=,tag:8+3f2yJMScYP1Pv1khN3cQ==,type:str]
    pgp:
        - created_at: "2025-11-13T12:00:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdjO6979FjmkSAQdAkrVG9SQviBtcpbSxn0ycGFWytf8EfjfqmrkRKDLRBWcw
            SmfiOK94Lo2exEoYWPNnBAuBcfAUBTRqov7ZKqPktoQYze3WRQzdeZErWNYn85/8
            1GYBCQIQjlWu3fhttHuG6DEHnurXVEqBid21MwiIkA5HIAMEh6HJ7OOsjD3D2/Jv
            XjaTtqL2JJ0rjX5GoRV2J48XpKTPMHQGe171oQSkNtsQoPYvCBoTMY7CZISJ4Poq
            E/MhjFz9scM=
            =bRH7
            -----END PGP MESSAGE-----
          fp: E90351D346AFCF25477190F1434316312E1CF3B1
    unencrypted_suffix: _unencrypted
    version: 3.10.2
