global:
    namespace: ENC[AES256_GCM,data:9jgqQizI,iv:qTdhGAdd+Fi06QpJpNG2WC+lFJ/DRLNViM0OJYWuZ1s=,tag:Cpf63CRPYwORALOwQ6Tdsg==,type:str]
    #ENC[AES256_GCM,data:/GZ34HXqpZzIjzUmZycdffnMltud4+LNKZy5w0SyO1OUdzGWBFwySDXyFyLjCwckjhfiBotm9iCQBtFaUFefl6is,iv:Z1S4CDRmKdXU3t46FlzP82aXUyYLPEr/2g+ZAPMCHuo=,tag:yjK81tq1O5i8l6Dj3iYR/Q==,type:comment]
    insecureSkipVerifySSL: ENC[AES256_GCM,data:7iNK5Q==,iv:WXGlfHGvIPxcAY11cZmrQzC/zk417WV/hcCtfzw2dk0=,tag:wMZ/SX0cR5N6sshc+LRbWw==,type:bool]
    ingress:
        domain: ENC[AES256_GCM,data:gktdGp3VE2Vmbs/PkNa5tdmXO3sNyE60,iv:+z2KfXnVJT2juHLsuakn0XabvyThiQLL/lgnnSX13pc=,tag:Y4maRyYMfSai8iOcc+6cUw==,type:str]
        commonAnnotations: {}
        tls:
            enabled: ENC[AES256_GCM,data:JASJ9+Q=,iv:JDs213rLoyhW3kXb1J1wM+KJMv1MylOJxm5mJ65FTMM=,tag:frjgYZGtxT03KQ3gOUgNrQ==,type:bool]
    secrets:
        k8sSecretCreator:
            apiToken: ENC[AES256_GCM,data:+cL+2SYWQHqOayyNDPoec3UsDlVhMFxEaNaR15pPCqRo9Qk=,iv:arysUcCbaFZSuNBebb3XWamRCR0MT+lyI5NPXP78xDY=,tag:5cGKUjxVFfqRUPIoaZ+fxg==,type:str]
        naavreCatalogueService:
            secretKey: ENC[AES256_GCM,data:f9jq2l0/srQ1K3abdqXmD4NSekXM2WaB6LPOQX0HsKN2f4dVxhiu5BJO,iv:iHAYUgzggSsts5hjAH25I5PQcoKO/r3mLVYoR3/zTB0=,tag:0edgyt/3lKObL/pCiUE47Q==,type:str]
            auth:
                superuser:
                    email: ENC[AES256_GCM,data:KOeXvPBvXbd/8uXLHdCqM6g=,iv:jkP0q7l+hC8oLmVRk8lAW0t7cTt4qNThZRI22WZTqvE=,tag:ei2mOONKS864Oh4ROxfMEQ==,type:str]
                    username: ENC[AES256_GCM,data:fIxWb+c=,iv:nfqJsiV1dBsQrkt7F0XifgSzTm6nArGvKsK2HL0QA/U=,tag:U5PjSuKZd5HyDqYvMxc0VQ==,type:str]
                    password: ENC[AES256_GCM,data:+YcT9ZkvJtEmjkoDKsNcvWVwfnnGKlDLJQQXuVBvSSO4P6rZODiKIHc9MMMtcA==,iv:/afxXCJwrpt46vb/dUK/iUip3eatuMnx/Cob3qyE1to=,tag:5yGPerk86XA4+TNlhwITew==,type:str]
            postgresql:
                password: ENC[AES256_GCM,data:0ra5L6KtcyPxZiIJvnsDCQo2Bz7VqDF7bpDiVo2yo1nnwrO88lssMHAZ6PmJO+9oDjA+,iv:ABLwjsMkIMaEiPCxgQGepVkNUHgMZAigW6seL+ErJ4E=,tag:+rSnkrX6T4YYkvSp5Q6Vbw==,type:str]
        naavrePaasFrontend:
            secretKey: ENC[AES256_GCM,data:UMNZx7obuqUIeIXi141kg5G5l5sNOGVfJyL3A0LmigMMp1sZeGo=,iv:FJZuXnE9eUJfk3mADVb1DdPbILIzqSZt61TMXH3lTY0=,tag:E6Vw5ZxxAKX8d9pIUW8waw==,type:str]
        keycloak:
            adminPassword: ENC[AES256_GCM,data:YEyFiGbi1Me5U8PaAice/yFrV80yAzg9Lw8ex8Z0,iv:i0qQCIVRPhl4RPD9L7Xg7AuajzzMyohQnsDjWajkDVE=,tag:A37NLSvEkl3KO1t1imWslg==,type:str]
            naavreClientSecret: ENC[AES256_GCM,data:OALFPRbUCFF/XCRECfeUn5b5+80reqWGOk2+WaLB0rdI+Y2/,iv:6+kbP9dhUIZihnR15dWnKG7dTgPrb8g9CW5HYrf4tr0=,tag:QpgIvkoY2cZ1sL9QwN8ryw==,type:str]
            users:
                - username: ENC[AES256_GCM,data:qgye02mO7w==,iv:9yXBg+VToR9wsm8cujyqGDOXC48U7LDCkuNaQEOHz+k=,tag:WbgD1VY+P/xuC5c2rSvxgg==,type:str]
                  password: ENC[AES256_GCM,data:qZlmVHw0893I1zA=,iv:6QO0ruyWjv9FwSGAebtx+es7ytZoK6kzc6ee2p8i8DI=,tag:uZK/b7DOXMTvJTI26EReTQ==,type:str]
            postgresql:
                password: ENC[AES256_GCM,data:PT/ci7uO7KPgAoepFS2+p6z3DCCzCqrk/MD4PEaXzovfT7Y=,iv:r8sqGUUP4eaZbGyOAjc5H7DsiA5bMDmK7PobWmvKCwo=,tag:5pyPFApZxFV1rIJj2lOLKw==,type:str]
jupyterhub:
    enabled: ENC[AES256_GCM,data:2pu4kg==,iv:b3roDEGy0FyaeTC3u8uYH+gunbs00KAF10Rl2FzNAiE=,tag:BNpFESsdLGr8I7pM1gE4Rw==,type:bool]
    vlabs:
        openlab:
            slug: ENC[AES256_GCM,data:QG+yWyRprA==,iv:ztT+zLmkJsENIhZ44S6x2eyhvr8xEvqaCCoIDRBp7oU=,tag:ullyTAMVY5qcGQQAwq77gw==,type:str]
            title: ENC[AES256_GCM,data:JeQuH1aOn/8QNZXgeTAU,iv:iqSQPTPwE2v6Qcl9/Loqe92xv+xOX9neA2pMRG6nYSo=,tag:KUsq6E5f/w4/R3kvfRCDfA==,type:str]
            description: ENC[AES256_GCM,data:tVdSSth6GkOK70uY46ZHreNcDH+21NsLT6SDEHrcEEbG7CFQRmg=,iv:ZQYq6YU8d126bX006QN1f6uf+gooejd5k41jVOVzAus=,tag:doJd6h/8EhdtL+q3R/ug9w==,type:str]
            image:
                name: ENC[AES256_GCM,data:galz/Mt7wUDKaEP/1DLgCo5j0EsGRsznDYELZm0p3pMZy8eCUvAhDdAzZlZcMBSM,iv:LMEoKZ7Q8JGZAhJcleS7E3Z8umDgH6OiWGbzO0uxJa4=,tag:Ws+7jVTAuWO3bf+t+AkldQ==,type:str]
                tag: ENC[AES256_GCM,data:Xgt+CHeJug==,iv:HyuciYg2Fmj/sjLMJiX/pdoHjto8fJJGNKa/96RWL6U=,tag:wSHFdfg2l595exNDlwnQFA==,type:str]
            configuration:
                base_image_tags_url: ENC[AES256_GCM,data:vYcidZzvCXEOOrkkxef1bprn/qeS3SHv/aD9ZFGwMFcpMvapPgaqbGLP2jUW8VvH9gM+1mzPB9X5Gw9lMwVtPAZhE1I6MQ8221dFVvZtkQ==,iv:8etxpBYO1GMi8qFK4eTSxUHIr8UCs48hGgHkrzwpCbw=,tag:bDiBEeqZcVyVvga5MMs6pA==,type:str]
                module_mapping_url: ENC[AES256_GCM,data:eBnVG4kiJC203LPKtAaJucNBxrWMunxTOJ0Q0MZHEr299WXeR21p48xLSsUwBXc5VlFwstU6pMrf6IYLDI+Rtq2wJWZlEO3gTwc0EA==,iv:rWQxJu6wcd6XqniZOc0xLhY9xPqpmqqr+J352wR1lIE=,tag:TctHGW+bmH/UfaapDp667Q==,type:str]
                cell_github_url: ENC[AES256_GCM,data:WVTy7iM/MEIy1cXH1XfDyyo/WXs8as5rtRSyWvbSUbi8E0A3QufOUqeS7so=,iv:Wm0ggUvH7f3sz7vCDP4ZBC3ETIbph8Fts7eYPNcR2pw=,tag:PXv104Kp2Za1vHXgNS4JlQ==,type:str]
                cell_github_token: ENC[AES256_GCM,data:VaOMkhme63W6PE3P1VA0y6/C9nurXxwENSPJTVNEBEjSNbJkaMpmsw==,iv:U2k+v+lhyAyzJTI4I5+8kznmIwvYdURwv2k62/UK3EE=,tag:fyLA8nKfWp5pTXG5sKqoKg==,type:str]
                registry_url: ENC[AES256_GCM,data:iQr+JYcDwSJ8biy5AM5AJv1Rs+OeO9NZsfiR7LAjgp3/,iv:JN4rvbb17Z/TxWkZb+LRSuCzkEcYDLvODubLvQr+sUU=,tag:p67aGAQ3wimhKXMYL5+rVQ==,type:str]
k8sSecretCreator:
    enabled: ENC[AES256_GCM,data:zAGuLQ==,iv:cFU1aS8cjRNMnaGVIXcxOrGYtbDqUoKYeboMVVyXpyc=,tag:+Sdh+jiNtfRnBXhfvBhwQQ==,type:bool]
naavreCatalogueService:
    enabled: ENC[AES256_GCM,data:CI9Kyw==,iv:UKwLVsiaWf35Gm+0RPnm85h5lu2vKk2WE3Gf6hm0i9Q=,tag:pS/FOftN73RCmfgU6OvCiQ==,type:bool]
naavreContainerizerService:
    enabled: ENC[AES256_GCM,data:FvFEP5Y=,iv:GnhXVlkjAHM6/qtAxz/jJSi+3ufYqq273gjYm9NXIhc=,tag:OnLI9IfRkDa3BP3aHPJngA==,type:bool]
    debug: ENC[AES256_GCM,data:ygUUPwA=,iv:ZND+Hajy7pNKUckN4hmqople9FxiYlGUZffUkZmev3I=,tag:Mgr1foHfNskAvGvnvEz59A==,type:bool]
naavreWorkflowService:
    enabled: ENC[AES256_GCM,data:kv/STg==,iv:9O8BBfRVXIMYVtq8kWwmkoBjwJCIyDQLEsOjrIfchAw=,tag:Qw9W7nYjJ2EkuaAzubjdqw==,type:bool]
naavrePaasFrontend:
    enabled: ENC[AES256_GCM,data:+2xA/Q==,iv:TnCgi24+cFGUTWWfD/ETljI+v2MDCe3a4RjMluZu8js=,tag:YN9loctL5Su8wZPMo77r0w==,type:bool]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:050752621342:key/4680e482-89c6-4210-b541-0453aa4a41ef
          created_at: "2025-11-13T12:00:46Z"
          enc: AQICAHhTmJtY4jHaV3j5UYiXyuOv54scxHoIVc/S99cT0IZ1IwF1mrxyuCEuzbUjXxcJ5nyhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1CmWUf45pcbnsGysAgEQgDtp85N+Zr2k2GOz5MfTVcylknAWRlgkpiqw6BikVPj6pdlsOcC4rd2z9mv3tDfqC59Xjtp40dwnTDIQrg==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:050752621342:key/6a9ef814-a13a-4299-b406-2e75b3ef1554
          created_at: "2025-11-13T12:00:46Z"
          enc: AQICAHi22G6tOL2LsvF6wpMHn/yuAwEASofH+f0dK2WYCvRIlQFKy+KsGup2RwsHUItLLd09AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDbc8JCZEDF8NcEUUAgEQgDvE+9877y6NsCfKDbCAdzRY7RpLV2e7V+rW7JKGqr0ELrx9L0IOpJ7vc7xbrrib+5jcPE6089yi+I3Quw==
          aws_profile: ""
    lastmodified: "2025-11-13T12:22:22Z"
    mac: ENC[AES256_GCM,data:wMTc/qGbVni38Sb/kJBafO0nmNQcTKTizg1sMt7U0io8KedKRmf6yCgoL+awu4SuQ4x9CHb4s0t7tpa1KyOIjmc8wMZbdsES3OiDeO47eq4J/vrSZ9HJc3eE8uMq2Uwvii2auFxTOlu9G+rLyGb27JJmeWp21tq+x4AstBBBSEA=,iv:JNsaziPG0OPLP5bKDLj/xYI/zPvnv3BXa7gSQELo3pg=,tag:zNwNjxFyQtuEddUfztQMBQ==,type:str]
    pgp:
        - created_at: "2025-11-13T12:00:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdjO6979FjmkSAQdAkrVG9SQviBtcpbSxn0ycGFWytf8EfjfqmrkRKDLRBWcw
            SmfiOK94Lo2exEoYWPNnBAuBcfAUBTRqov7ZKqPktoQYze3WRQzdeZErWNYn85/8
            1GYBCQIQjlWu3fhttHuG6DEHnurXVEqBid21MwiIkA5HIAMEh6HJ7OOsjD3D2/Jv
            XjaTtqL2JJ0rjX5GoRV2J48XpKTPMHQGe171oQSkNtsQoPYvCBoTMY7CZISJ4Poq
            E/MhjFz9scM=
            =bRH7
            -----END PGP MESSAGE-----
          fp: E90351D346AFCF25477190F1434316312E1CF3B1
    unencrypted_suffix: _unencrypted
    version: 3.10.2
