global:
  namespace: naavre
jupyterhub:
  vlabs:
    openlab:
      image:
        tag: v0.0.38
      configuration:
        base_image_tags_url: https://github.com/NaaVRE/flavors/releases/latest/download/base_image_tags.json
        cell_github_url: https://github.com/NaaVRE/cells-vl-tests
        cell_github_token: ghp_XXXXXXXXXXXXXXXX
        registry_url: ghcr.io/naavre/naavre-cells-vl-tests
        module_mapping_url: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json

naavreContainerizerService:
  enabled: false

naavreWorkflowService:
  enabled: false

naavrePaasFrontend:
  enabled: false