global:
    namespace: ENC[AES256_GCM,data:9jgqQizI,iv:qTdhGAdd+Fi06QpJpNG2WC+lFJ/DRLNViM0OJYWuZ1s=,tag:Cpf63CRPYwORALOwQ6Tdsg==,type:str]
jupyterhub:
    vlabs:
        openlab:
            image:
                tag: ENC[AES256_GCM,data:Xgt+CHeJug==,iv:HyuciYg2Fmj/sjLMJiX/pdoHjto8fJJGNKa/96RWL6U=,tag:wSHFdfg2l595exNDlwnQFA==,type:str]
            configuration:
                base_image_tags_url: ENC[AES256_GCM,data:JIsAoijUGQnoSfH+S6OwNM1b78XaZTBo1tGhyC3RjK5TxUP9M44LrZNGfvHnxs29Fp50fYh1j5b6FUZntluV2IQR5ZN0E8gSI34VhJrOOOo=,iv:eohDqrBjztZowv8H1/I4Gpq4joh4IiJd8A8THAmXcfM=,tag:9aN+/rmbJu1y58wE0Tdc9Q==,type:str]
                cell_github_url: ENC[AES256_GCM,data:WVTy7iM/MEIy1cXH1XfDyyo/WXs8as5rtRSyWvbSUbi8E0A3QufOUqeS7so=,iv:Wm0ggUvH7f3sz7vCDP4ZBC3ETIbph8Fts7eYPNcR2pw=,tag:PXv104Kp2Za1vHXgNS4JlQ==,type:str]
                cell_github_token: ENC[AES256_GCM,data:VaOMkhme63W6PE3P1VA0y6/C9nurXxwENSPJTVNEBEjSNbJkaMpmsw==,iv:U2k+v+lhyAyzJTI4I5+8kznmIwvYdURwv2k62/UK3EE=,tag:fyLA8nKfWp5pTXG5sKqoKg==,type:str]
                registry_url: ENC[AES256_GCM,data:iQr+JYcDwSJ8biy5AM5AJv1Rs+OeO9NZsfiR7LAjgp3/,iv:JN4rvbb17Z/TxWkZb+LRSuCzkEcYDLvODubLvQr+sUU=,tag:p67aGAQ3wimhKXMYL5+rVQ==,type:str]
naavreContainerizerService:
    enabled: ENC[AES256_GCM,data:esy0ug==,iv:IWeEguJXX9hnRx8lDTfZQBb/Amcs4LipVtM2ig1eoJ0=,tag:WTYs3Y3K1Y04g7CRbRbeEg==,type:bool]
csi-s3:
    enabled: ENC[AES256_GCM,data:Jkolow==,iv:PsnKb+PxqN/0jDfc1lp3eTzPH0bBJitgEH1XtT1QBnE=,tag:fGTn5rFS8AK/XnIcZxsmaw==,type:bool]
    secret:
        #ENC[AES256_GCM,data:4Tv9RZYHzasHa3aTeaDyVYfPTSnMCc/7jGAT2FQNxssMrkoDI6liQYFb8VayewE=,iv:cFNiqmt4/NFr+zY/tv4mXTYXIURYeLjkfO1KJfbzGN4=,tag:clajQZTP0+ByrLcGSKMMmQ==,type:comment]
        create: ENC[AES256_GCM,data:PvYEMw==,iv:hqanzd618X9Qzrv40ENFd7p9qv3Hf3SpcpqAZCr9jWg=,tag:b10iiJaui+1bD1wxJZO8fA==,type:bool]
        #ENC[AES256_GCM,data:9H4NtjHGUsi5pj8EZYk=,iv:ISdLhZzh4dhDRKe9DLzZ3TrAGrviTaERmRN5dF/Xcy4=,tag:wBG31H3Y4NXnDOzvqpbgcA==,type:comment]
        accessKey: ENC[AES256_GCM,data:9cz6IX3afMk0inV+,iv:+oq062sJes7z0pDZJV1MwggfpgTvRnf/vEMqeyqdyys=,tag:elVWJTI7R8v2fqPc1a5JDQ==,type:str]
        #ENC[AES256_GCM,data:ml03FuBneJvjjetpGNA=,iv:PTf5+F8N72vHxnR8FVgChfDzbCXnJqiDDZTsnU1N7QE=,tag:7Go+Ua2ka8mPtX95VD75Hw==,type:comment]
        secretKey: ENC[AES256_GCM,data:MiqTYOkCVKNFwTKt9/+7a1bCztZGkP2KQLOhwUyq24kjRm0WmrYPIQ==,iv:KPtgCSMGpD2/Fogxfdvh7pCaNwFeFCAkCjy89sD6hrs=,tag:CFDztaRmRJbAWfVZ/AM8Ug==,type:str]
        endpoint: ENC[AES256_GCM,data:4zfhvVOzMFedOwpsyb3uo2+Cm+rz4Jp80+nZ6UENQoVbK2o2BQ==,iv:DnTeOE3lpKcvlnkIy6hYe3XHpN+BTiquqQ3p4Q+tXqU=,tag:njTRdSbvrwReqj6EvqsttA==,type:str]
        region: ENC[AES256_GCM,data:iiOxSwFN43f+qVk=,iv:zYI3eCsMx1gNBvP0Ludh5YglJVopYQe7jIoxvP+vurw=,tag:q0P0rj/cOaKP5BRgmUOdqQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:050752621342:key/4680e482-89c6-4210-b541-0453aa4a41ef
          created_at: "2025-11-13T12:00:46Z"
          enc: AQICAHhTmJtY4jHaV3j5UYiXyuOv54scxHoIVc/S99cT0IZ1IwF1mrxyuCEuzbUjXxcJ5nyhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1CmWUf45pcbnsGysAgEQgDtp85N+Zr2k2GOz5MfTVcylknAWRlgkpiqw6BikVPj6pdlsOcC4rd2z9mv3tDfqC59Xjtp40dwnTDIQrg==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:050752621342:key/6a9ef814-a13a-4299-b406-2e75b3ef1554
          created_at: "2025-11-13T12:00:46Z"
          enc: AQICAHi22G6tOL2LsvF6wpMHn/yuAwEASofH+f0dK2WYCvRIlQFKy+KsGup2RwsHUItLLd09AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDbc8JCZEDF8NcEUUAgEQgDvE+9877y6NsCfKDbCAdzRY7RpLV2e7V+rW7JKGqr0ELrx9L0IOpJ7vc7xbrrib+5jcPE6089yi+I3Quw==
          aws_profile: ""
    lastmodified: "2025-11-19T13:12:05Z"
    mac: ENC[AES256_GCM,data:RfCsFhdacbBkQEyfDZgMU23P9IqMztwBtTNmO5uEQAp1AmPXDfBtNBpaAUVIwyrduDwsDPtISyvRrxNwLqxLQrIHFVkDuJF8w2vcU7uhXhMH9/77oWr1lF6i4DGDD6sFDBrkQluLtOBSs242zbxuFoy014D5m77zAsv7qKQMntQ=,iv:tK+pMU5Ir6jxLfrlr9S9ECbzigwd6gEenqOuzbnzplg=,tag:PirPYqB4A8NDs/F+PHTRTw==,type:str]
    pgp:
        - created_at: "2025-11-13T12:00:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdjO6979FjmkSAQdAkrVG9SQviBtcpbSxn0ycGFWytf8EfjfqmrkRKDLRBWcw
            SmfiOK94Lo2exEoYWPNnBAuBcfAUBTRqov7ZKqPktoQYze3WRQzdeZErWNYn85/8
            1GYBCQIQjlWu3fhttHuG6DEHnurXVEqBid21MwiIkA5HIAMEh6HJ7OOsjD3D2/Jv
            XjaTtqL2JJ0rjX5GoRV2J48XpKTPMHQGe171oQSkNtsQoPYvCBoTMY7CZISJ4Poq
            E/MhjFz9scM=
            =bRH7
            -----END PGP MESSAGE-----
          fp: E90351D346AFCF25477190F1434316312E1CF3B1
    unencrypted_suffix: _unencrypted
    version: 3.10.2
